In [1]:
from src import *

In [ ]:
def loadnpz(file):
    file = os.path.expanduser(file)
    npz = np.load(file, allow_pickle=True)
    meta = npz['metadata'].item()
    meta_ = MetaData(meta.measurement, meta.ground_truth, 'frequency', meta.amplitude, meta.pwm_duty, timestamp=meta.timestamp)

    dic = {}
    for k in npz.files:
        if k.lower() == 'noise':
            dic['background'] = npz[k]
        
        elif k.lower() == 'frequency_estimates':
            dic['estimates_a'] = npz[k]

        elif k.lower() == 'metadata':
            dic[k] = meta_

        elif k.lower() == 'velocity_estimates':
            pass

        elif k.lower() == 'start_point_estimates':
            pass

        else:
            dic[k] = npz[k]

    return Estimates(**dic)

In [ ]:
from glob import glob

In [ ]:
tree = [
    'noisy/di_5px',
    'noisy/spade_5px',

    '0noise/di_5px',
    '0noise/spade_5px',

    '0noise/di_3px',
    '0noise/spade_3px',
]

In [ ]:
def main(_folder):
    src = os.path.join('__estimates__.old', _folder)
    dst = os.path.join('__estimates__', _folder)
    for file in tqdm(glob(src+'/*')):
        c = loadnpz(file)
        c.savez(dst)


In [2]:
c = LoadEstimates(r'__estimates__\0noise\di_3px\di_3px_f0.1_d0.npz')

In [4]:
c = Estimation.FromEstimates(c)

In [5]:
c

cropped_data: [[[217. 206. 198. ... 200. 204. 201.]
  [198. 208. 197. ... 198. 200. 199.]
  [210. 198. 211. ... 199. 198. 204.]
  ...
  [198. 205. 212. ... 199. 202. 203.]
  [207. 199. 202. ... 209. 198. 202.]
  [198. 196. 198. ... 211. 208. 203.]]

 [[201. 195. 210. ... 202. 206. 200.]
  [201. 218. 192. ... 198. 206. 195.]
  [197. 208. 200. ... 199. 202. 201.]
  ...
  [198. 197. 206. ... 198. 200. 203.]
  [213. 210. 199. ... 203. 205. 198.]
  [209. 204. 199. ... 214. 200. 204.]]

 [[200. 207. 204. ... 197. 193. 194.]
  [199. 208. 198. ... 198. 206. 198.]
  [222. 199. 202. ... 201. 200. 198.]
  ...
  [197. 202. 198. ... 197. 204. 196.]
  [198. 198. 207. ... 198. 201. 199.]
  [211. 198. 197. ... 195. 199. 196.]]

 ...

 [[196. 196. 208. ... 202. 200. 198.]
  [194. 196. 206. ... 200. 197. 201.]
  [207. 193. 203. ... 202. 198. 199.]
  ...
  [199. 201. 197. ... 201. 192. 196.]
  [196. 199. 203. ... 205. 201. 211.]
  [198. 201. 198. ... 200. 198. 203.]]

 [[195. 195. 209. ... 219. 201. 193.